export const EventsData = [
  {
    id: 1,
    label: "Classical Solo Dance",
    participants: "01",
    timeLimit: "3+2 Min",
    NoTeams: "3",
    rules: [],
    Category: "Dance",
    EntryFee: "150",
    Time: "Day 1 (9-06-2023) 11 AM",
    Link: "https://forms.gle/j63ZL5MhD3aGVcWn9",
  },
  {
    id: 2,
    label: "Classical Group Dance",
    participants: "06 Max",
    timeLimit: "4+2 Min",
    NoTeams: "3",
    rules: [],
    Category: "Dance",
    EntryFee: "300",
    Time: "Day 2 (18-06-2022) 11 AM",
    Link: "https://rzp.io/l/WMuA79THh",
  },
  {
    id: 3,
    label: "Duet Dance",
    participants: "02",
    timeLimit: "4+2 Min",
    NoTeams: "3",
    rules: ["No Gender Restriction (M+M),(M+F),(F+F)"],
    Category: "Dance",
    EntryFee: "200",
    Time: "Day 2 (18-06-2022) 12 PM",
    Link: "https://rzp.io/l/ROMZcA1UxI",
  },
  {
    id: 4,
    label: "Western Solo",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "3",
    rules: [],
    Category: "Dance",
    EntryFee: "150",
    Time: "Day 2 (18-06-2022) 1 PM",
    Link: "https://rzp.io/l/iwnUCXug",
  },
  {
    id: 5,
    label: "Choreography",
    participants: "08 Max",
    timeLimit: "6+2 Min",
    NoTeams: "3",
    rules: [
      "The teams may consist of all boys, all girls or a combination of both boys and girls",
      "The no of accompainsts permmissible is 5",
      "Information about the theme has to be submitted in hardcopy",
      "Participating teams are responsible for removal of their sets, belongings etc, Immediately after the completion of their performance",
      "Judgement will be based on the basis of theme, rhythm, formation, expression coustumes, makeup, settings and on overall effect.",
      "Pre-Recorded CDs or pendrives maybe be used",
    ],
    Category: "Dance",
    EntryFee: "500",
    Time: "Day 2 (18-06-2022) 2:30 PM",
    Link: "https://rzp.io/l/Is3TaWcWVk",
  },
  {
    id: 6,
    label: "Classical Vocal",
    participants: "01",
    timeLimit: "9+3 Min",
    NoTeams: "3",
    rules: [
      "Time for stage or instrument setting is max 3 min",
      "Judgement will be based on the qualities like selections of raaga, kruthi, alapana, composition and general impression",
      "Max no of accompanying artists 2",
    ],
    Category: "Sing",
    EntryFee: "150",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/Ibea3Rywz",
  },
  {
    id: 7,
    label: "Western Vocal Solo",
    participants: "01",
    timeLimit: "6+2 Min",
    NoTeams: "3",
    rules: [
      "Time for stage or instrument setting in max 3 min",
      "Judgement will be based on the qualities like choice of song Incooperating dynamics , expressive musical feelings and overall presentation",
      "Use of karaoke is allowed",
    ],
    Category: "Sing",
    EntryFee: "150",
    Time: "Day 1 (17-06-2022) 2 PM",
    Link: "https://rzp.io/l/M6rAYm70Y",
  },
  {
    id: 8,
    label: "Instrumental Solo(Precursion) Carnatic or Hindustani or Western",
    participants: "01",
    timeLimit: "8+2 Min",
    NoTeams: "3",
    rules: [
      "Time for stage or instrument setting is max 3 min",
      "Max no of accompanists allowed is 1",
      "Judgement will be based on the choice of the taala and ability to present the nuances of the chosen taala",
    ],
    Category: "Sing",
    EntryFee: "150",
    Time: "Day 1 (17-06-2022) 3 PM",
    Link: "https://rzp.io/l/D364mC1x0H",
  },
  {
    id: 9,
    label:
      "Instrumental Solo(non Precursion) Carnatic or Hindustani or Western",
    participants: "01",
    timeLimit: "8+2 Min",
    NoTeams: "3",
    rules: [
      "Time for stage or instrumental settings is max 3 min",
      "Judgement will be raga, krirti, alapana, swara prastara, time management and dress code",
      "Max no of accompanying artists is 2",
    ],
    Category: "Sing",
    EntryFee: "150",
    Time: "Day 1 (17-06-2022) 3 PM",
    Link: "https://rzp.io/l/sybtfFl",
  },
  {
    id: 10,
    label: "Light Music solo (Indian)",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "3",
    rules: [
      "Time for stage or instrumental settings is max 3 minutes",
      "Max no of accompanists is 2",
      "Classical sonngs and film songs are not allowed",
      "Judgement will be based on the choice of song, incorporating dynamincs , expressive musical feelings and overall presentation",
      "Use of karaoke is allowed",
    ],
    Category: "Sing",
    EntryFee: "150",
    Time: "Day 1 (17-06-2022) 3 PM",
    Link: "https://rzp.io/l/P40oV8mjLg",
  },
  {
    id: 11,
    label: "Battle of Bands",
    participants: "08 Max",
    timeLimit: "8+2 Min",
    NoTeams: "1",
    rules: [
      "Set Up time is 5 min",
      "Cross college teams are not allowed",
      "karaoke programmed music and special effects and not allowed",
      "Songs performed by the bands may be in any language",
      "Bands have to bring their own equipments",
      "Only the drum kit will be provided",
      "Minimum no of vocalists should be 3",
      "Maximum no of instruments allowed will be 4",
    ],
    Category: "Sing",
    EntryFee: "500",
    Time: "Day 1 (17-06-2022) 3 PM",
    Link: "https://rzp.io/l/Qm0Wk2w3k",
  },
  {
    id: 12,
    label: "Duet singing",
    participants: "02",
    timeLimit: "3+2 Min",
    NoTeams: "3",
    rules: [
      "Any combinations of male and female are allowed",
      "Karaoke or max of 2 accompanists are allowed",
      "Judgement will be based on solely on vocals",
    ],
    Category: "Fine Arts",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 4 PM",
    Link: "https://rzp.io/l/gItSYeDE",
  },
  {
    id: 13,
    label: "The Gag spectacle (Stand-up comedy)",
    participants: "01",
    timeLimit: "3+2 Min",
    NoTeams: "3",
    rules: [
      "Script should be submitted 30 min before tbe start of the eveng for verification",
    ],
    Category: "Theatre",
    EntryFee: "100",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/GN45ZGEhC",
  },
  {
    id: 14,
    label: "The (Un) scripted tales (Skit)",
    participants: "Max 12",
    timeLimit: "10 Min",
    NoTeams: "3",
    rules: [
      "Props and costumes are allowed",
      "The performance should not be a part of any movie or TV show",
    ],
    Category: "Theatre",
    EntryFee: "600",
    Time: "Day 2 (18-06-2022) 11 AM",
    Link: "https://rzp.io/l/MH5eVle",
  },
  {
    id: 15,
    label: "JIT pe Bechde! (MadAds)",
    participants: "Max 10",
    timeLimit: "6 Min",
    NoTeams: "3",
    rules: [
      "Props are costumes are allowed",
      "The performance should not be any movie or TV show",
      "Judgements will be based on Ads",
      "Vulgarity and obscenity in any form is not allowed",
    ],
    Category: "Theatre",
    EntryFee: "600",
    Time: "Day 2 (18-06-2022) 12 PM",
    Link: "https://rzp.io/l/rd1sPxD0O",
  },
  {
    id: 16,
    label: "Short Movie Making",
    participants: "3",
    timeLimit: "-",
    NoTeams: "3",
    rules: [
      "Video has to be done in prior with a glimpse of time lapse.",
      "All the video clips taken must be shown to the judges.",
    ],
    Category: "Theatre",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/D44AvAHqW",
  },
  // {
  //   id: 17,
  //   label: "Movie Making",
  //   participants: "Max 3",
  //   timeLimit: "Not Defiened",
  //   NoTeams: "3",
  //   rules: [],
  //   Category: "Theatre",
  //   EntryFee: "500",
  //   Link: "https://rzp.io/l/OxLnwI8y2G",
  // },
  {
    id: 18,
    label: "Give Me A Minute (JAM)",
    participants: "01",
    timeLimit: "1 Min",
    NoTeams: "3",
    rules: [
      "Candidates would be objected for the following reasons.",
      "Usage of slang, direct speech & abbrievations.",
      "No plagiarism or redundancy",
      "Deviation from the topic/time wasting tactics not allowed.",
      "Unnecessary stress or obsession with words, incoherence or dramatization",
      "Standard format not to be used.",
    ],
    Category: "Literary",
    EntryFee: "100",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/FVL5S0kT9x",
  },
  {
    id: 19,
    label: "Word Battle (Debate)",
    participants: "02",
    timeLimit: "5 Min per speaker",
    NoTeams: "3",
    rules: [
      "Topic will be 24 hrs prior to the event",
      "One participant speaks for the topic while the other against it.",
      "Each participant speaks for 4 mins.",
      "After each teams speaks, 2 mins is allowed for rebutting.",
      "Judges as well as audience may ask questions.",
    ],
    Category: "Literary",
    EntryFee: "200",
    Time: "Day 2 (18-06-2022) 12 PM",
    Link: "https://rzp.io/l/S34dPxiO",
  },
  {
    id: 20,
    label: "What's the pantomime? (Dumb Charades)",
    participants: "03",
    timeLimit: "3 Rounds",
    NoTeams: "3",
    rules: [
      "Each member of the team needs to enact at least once in a round.",
      "General DC rules apply.",
      "Top teams qualify for the finals",
    ],
    Category: "Literary",
    EntryFee: "300",
    Time: "Day 2 (18-06-2022) 1:30 PM",
    Link: "https://rzp.io/l/oYqT1hiC",
  },
  {
    id: 21,
    label: "Erudite Ambition (Quiz)",
    participants: "02",
    timeLimit: "-",
    NoTeams: "3",
    rules: [
      "No of rounds will be decided by the Quiz Master.",
      "One written preliminary test.",
      "Top teams will be selected for the finals.",
    ],
    Category: "Literary",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 2:30 PM",
    Link: "https://rzp.io/l/10thzo0",
  },
  {
    id: 22,
    label: "Antyakshari (Kannada)",
    participants: "02",
    timeLimit: "",
    NoTeams: "3",
    rules: [
      "No of rounds will be decided by the judges.",
      "One written preliminary test will be given, from Kannada movies.",
      "Selected teams will participate in the finals.",
    ],
    Category: "Literary",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/sLxInDzqx",
  },
  {
    id: 23,
    label: "Its all in the face! (Face Painting)",
    participants: "02",
    timeLimit: "60 Min",
    NoTeams: "3",
    rules: [
      "Topic will be given on spot.",
      "Paints & brushes will be provided (max 6 colors).",
      "Provisions - waste cloth, paper, water, plastic cups.",
    ],
    Category: "Fine Arts",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/FYOE9bI",
  },
  {
    id: 24,
    label: "Picture perfect through my lens (Creative Photography)",
    participants: "01",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: [
      "Editing photos is not allowed.",
      "Only cam pictures should be produced in USB portable media storage device(.jpg,.jpeg,.tif).",
      "Downloaded photographs not allowed.",
      "The photos has to be taken in the campus.",
      "Art must be explained.",
    ],
    Category: "Fine Arts",
    EntryFee: "100",
    Time: "Day 2 (18-06-2022) FULL DAY",
    Link: "https://rzp.io/l/isNRyT51F",
  },
  {
    id: 25,
    label: "The Poster Project (Collage)",
    participants: "02",
    timeLimit: "90 Min",
    NoTeams: "3",
    rules: [
      "Topics will be given on spot.",
      "Chart paper and glue will be provided.",
      "No other items will be provided.",
      "Scissors & burning of papers is prohibited.",
      "Participants will not be allowed to leave the hall during the event.",
    ],
    Category: "Fine Arts",
    EntryFee: "200",
    Time: "Day 2 (18-06-2022) 11:30 AM",
    Link: "https://rzp.io/l/cX7jNHHJ7",
  },
  {
    id: 26,
    label: "Counter Strike",
    participants: "04",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: [
      "The maps selected for the competition are dedust2, de_inferno, de_nuke, de_train.",
      "Official ESLONE gaming rules will be followed, except for no of rounds allotted.",
      "Offline",
    ],
    Category: "Gaming",
    EntryFee: "200",
    Time: "Day 2 (18-06-2022) 11 AM",
    Link: "https://rzp.io/l/FRmQE1B",
  },
  {
    id: 27,
    label: "Valorant",
    participants: "05",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: [
      "The maps selected for the competition Bind, Ice box, Ascent, Split, Breeze.",
      "Official VCT gaming rules will be followed.",
      "Online",
    ],
    Category: "Gaming",
    EntryFee: "250",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/hiJPjk2",
  },
  {
    id: 28,
    label: "Unleash your inner Indiana Jones (Treasure Hunt)",
    participants: "04",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: ["Details Will be provided at the venue.", "Offline"],
    Category: "Gaming",
    EntryFee: "200",
    Time: "Day 2 (18-06-2022) 10:30 AM",
    Link: "https://rzp.io/l/th4OyRZZG",
  },
  {
    id: 29,
    label: "BGMI(solo)",
    participants: "01",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: ["Deatils Will be provided at the venue.", "Offline"],
    Category: "Gaming",
    EntryFee: "50",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/E6dWmLM2Ao",
  },
  {
    id: 30,
    label: "BGMI(squad)",
    participants: "04",
    timeLimit: "No limit",
    NoTeams: "3",
    rules: ["Deatils Will be provided at the venue.", "Offline"],
    Category: "Gaming",
    EntryFee: "200",
    Time: "Day 1 (17-06-2022) 1 PM",
    Link: "https://rzp.io/l/AECs0JvG",
  },
  {
    id: 31,
    label: "Vogue Blooded",
    participants: "10-12",
    timeLimit: "10 Min",
    NoTeams: "3",
    rules: [
      "Karaoke is allowed.",
      "Vulgarity and indecent acts on stage will lead to disqualification.",
    ],
    Category: "Gaming",
    EntryFee: "1400",
    Time: "Day 1 (17-06-2022) 5:30 PM",
    Link: "https://rzp.io/l/SkXGa4IFR",
  },
];

export const EventsDataDance = [
  {
    id: 1,
    label: "Dance Classical Solo",
    Category: "Dance",
    EntryFee: "150",
  },
  {
    id: 2,
    label: "Dance Classical Group",
    Category: "Dance",
    EntryFee: "300",
  },
  {
    id: 3,
    label: "Duet Dance",
    Category: "Dance",
    EntryFee: "200",
  },
  { id: 4, label: "Western Solo", Category: "Dance", EntryFee: "150" },
  {
    id: 5,
    label: "Choreography",
    Category: "Dance",
    EntryFee: "500",
  },
];

export const EventsDataMusic = [
  {
    id: 6,
    label: "Classic(Karnatic or Hindustani)",
    Category: "Music",
    EntryFee: "150",
  },
  { id: 7, label: "Western Solo", Category: "Music", EntryFee: "150" },
  {
    id: 8,
    label: "Instrumental Solo(percussion)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 9,
    label: "Instrumental Solo(Non percussion)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 10,
    label: "Light Music Solo(Indian)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 11,
    label: "Battle of bands(Indian)",
    Category: "Music",
    EntryFee: "500",
  },
  { id: 12, label: "Duet Singing", Category: "Music", EntryFee: "200" },
];

export const EventsDataTheater = [
  {
    id: 13,
    label: "The Gag Spectacle (Stand-up comedy)",
    Category: "Theater",
    EntryFee: "100",
  },
  {
    id: 14,
    label: "The (Un)scripted tales! (skit)",
    Category: "Theater",
    EntryFee: "600",
  },
  {
    id: 15,
    label: "JIT pe Bechde! (MadAds)",
    Category: "Theater",
    EntryFee: "600",
  },
  { id: 16, label: "Short Movie Making", Category: "Theater", EntryFee: "200" },
  // { id: 17, label: "Movie Making", Category: "Theater", EntryFee: "500" },
];

export const EventsDataLiterary = [
  {
    id: 18,
    label: "Give Me A Minute (JAM)",
    Category: "Literary",
    EntryFee: "100",
  },
  {
    id: 19,
    label: "Word Battle (Debate)",
    Category: "Literary",
    EntryFee: "200",
  },
  {
    id: 20,
    label: "What's the pantomime? (Dumb Charades)",
    Category: "Literary",
    EntryFee: "300",
  },
  {
    id: 21,
    label: "Erudite Ambition (Quiz)",
    Category: "Literary",
    EntryFee: "200",
  },
  {
    id: 22,
    label: "Antyakshari(Kannada)",
    Category: "Literary",
    EntryFee: "200",
  },
];
export const EventsDataFinearts = [
  {
    id: 23,
    label: "Its all in the face! (Face Painting)",
    Category: "Fine arts",
    EntryFee: "200",
  },
  {
    id: 24,
    label: "Picture perfect through my lens (Creative Photography)",
    Category: "Fine arts",
    EntryFee: "100",
  },
  {
    id: 25,
    label: "The Poster Project (Collage)",
    Category: "Fine arts",
    EntryFee: "200",
  },
];
export const EventsDataGaming = [
  {
    id: 26,
    label: "Counter Strike(At Venue)",
    Category: "Gaming",
    EntryFee: "200",
  },
  { id: 27, label: "Valorant(Online)", Category: "Gaming", EntryFee: "250" },
  {
    id: 28,
    label: "Unleash your inner Indiana Jones(Treasure Hunt)",
    Category: "Gaming",
    EntryFee: "200",
  },
  {
    id: 29,
    label: "BGMI(solo)",
    participants: "01",
    EntryFee: "50",
  },
  {
    id: 30,
    label: "BGMI(squad)",
    participants: "04",
    EntryFee: "200",
  },
];

export const EventsDataFashion = [
  {
    id: 31,
    label: "Vogue Blooded",
    Category: "Gaming",
    EntryFee: "1400",
  },
];
