export const EventsData = [
  {
    id: 1,
    label: "Classical Solo Dance",
    participants: "01",
    timeLimit: "3+2 Min",
    NoTeams: "2",
    rules: [],
    Category: "Dance",
    EntryFee: "100",
  },
  {
    id: 2,
    label: "Classical Group Dance",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "2",
    rules: [],
    Category: "Dance",
    EntryFee: "500",
  },
  {
    id: 3,
    label: "Duet Dance",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "2",
    rules: ["No Gender Restriction (M+M),(M+F),(F+F)"],
    Category: "Dance",
    EntryFee: "300",
  },
  {
    id: 4,
    label: "Western Solo",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "2",
    rules: [],
    Category: "Dance",
    EntryFee: "150",
  },
  {
    id: 5,
    label: "Choreography",
    participants: "01",
    timeLimit: "6+2 Min",
    NoTeams: "2",
    rules: [
      "The teams may consist of all boys, all girls or a combination of both boys and girls",
      "The no of accompainsts permmissible is 5",
      "Information about the theme has to be submitted in hardcopy",
      "4",
      "5",
      "6",
    ],
    Category: "Dance",
    EntryFee: "500",
  },
  {
    id: 6,
    label: "Classical Vocal",
    participants: "01",
    timeLimit: "9+3 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Sing",
    EntryFee: "150",
  },
  {
    id: 7,
    label: "Western Vocal Solo",
    participants: "01",
    timeLimit: "6+2 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Sing",
    EntryFee: "150",
  },
  {
    id: 8,
    label: "Instrumental Solo(Precursion) Carnatic or Hindustani or Western",
    participants: "01",
    timeLimit: "8+2 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Sing",
    EntryFee: "150",
  },
  {
    id: 9,
    label:
      "Instrumental Solo(non Precursion) Carnatic or Hindustani or Western",
    participants: "01",
    timeLimit: "8+2 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Sing",
    EntryFee: "150",
  },
  {
    id: 10,
    label: "Light Music solo (Indian)",
    participants: "01",
    timeLimit: "4+2 Min",
    NoTeams: "2",
    rules: ["1", "2", "3", "4", "5"],
    Category: "Sing",
    EntryFee: "150",
  },
  {
    id: 11,
    label: "Battle of Bands",
    participants: "07",
    timeLimit: "8+2 Min",
    NoTeams: "1",
    rules: ["1", "2", "3", "4", "5", "6", "7", "8"],
    Category: "Sing",
    EntryFee: "500",
  },
  {
    id: 12,
    label: "Duet singing",
    participants: "02",
    timeLimit: "3+2 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Fine Arts",
    EntryFee: "300",
  },
  {
    id: 13,
    label: "Stand up comedy",
    participants: "01",
    timeLimit: "3+2 Min",
    NoTeams: "2",
    rules: ["1"],
    Category: "Theatre",
    EntryFee: "150",
  },
  {
    id: 14,
    label: "Skit",
    participants: "11",
    timeLimit: "10 Min",
    NoTeams: "2",
    rules: ["1", "2"],
    Category: "Theatre",
    EntryFee: "600",
  },
  {
    id: 15,
    label: "MadAds",
    participants: "12",
    timeLimit: "6 Min",
    NoTeams: "2",
    rules: ["1", "2", "3", "4"],
    Category: "Theatre",
    EntryFee: "600",
  },
  {
    id: 16,
    label: "Short Movie Making",
    participants: "3",
    timeLimit: "Not Defiened",
    NoTeams: "2",
    rules: ["1", "2", "3", "4"],
    Category: "Theatre",
    EntryFee: "200",
  },
  {
    id: 17,
    label: "Movie Making",
    participants: "Max 3",
    timeLimit: "Not Defiened",
    NoTeams: "2",
    rules: ["1", "2", "3", "4"],
    Category: "Theatre",
    EntryFee: "500",
  },
  {
    id: 18,
    label: "Just a minute",
    participants: "01",
    timeLimit: "1 Min",
    NoTeams: "2",
    rules: ["1", "2", "3", "4", "5", "6"],
    Category: "Literary",
    EntryFee: "100",
  },
  {
    id: 19,
    label: "Debate",
    participants: "02",
    timeLimit: "5 Min",
    NoTeams: "3",
    rules: ["1", "2", "3", "4", "5"],
    Category: "Literary",
    EntryFee: "200",
  },
  {
    id: 20,
    label: "Dumb Charades",
    participants: "03",
    timeLimit: "3 Rounds",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Literary",
    EntryFee: "300",
  },
  {
    id: 21,
    label: "Quiz",
    participants: "02",
    timeLimit: "",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Literary",
    EntryFee: "200",
  },
  {
    id: 22,
    label: "Antyakshari (Kannada)",
    participants: "03",
    timeLimit: "",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Literary",
    EntryFee: "150",
  },
  {
    id: 23,
    label: "Face Painting",
    participants: "02",
    timeLimit: "60 Min",
    NoTeams: "2",
    rules: ["1", "2", "3"],
    Category: "Fine Arts",
    EntryFee: "200",
  },
  {
    id: 24,
    label: "Creative Photography",
    participants: "01",
    timeLimit: "No limit",
    NoTeams: "2",
    rules: ["1", "2", "3", "4", "5"],
    Category: "Fine Arts",
    EntryFee: "100",
  },
  {
    id: 25,
    label: "Collage",
    participants: "02",
    timeLimit: "90 Min",
    NoTeams: "2",
    rules: ["1", "2", "3", "4", "5"],
    Category: "Fine Arts",
    EntryFee: "150",
  },
  {
    id: 26,
    label: "Counter Strike",
    participants: "05",
    timeLimit: "No limit",
    NoTeams: "Open Event",
    rules: ["1", "2", "Offline"],
    Category: "Gaming",
    EntryFee: "200",
  },
  {
    id: 27,
    label: "Valorant",
    participants: "05",
    timeLimit: "No limit",
    NoTeams: "Open Event",
    rules: ["1", "2", "Online"],
    Category: "Gaming",
    EntryFee: "250",
  },
  {
    id: 28,
    label: "Treasure Hunt",
    participants: "06",
    timeLimit: "No limit",
    NoTeams: "Open Event",
    rules: ["Deatils Will be provided at the venue", "Offline"],
    Category: "Gaming",
    EntryFee: "200",
  },
  {
    id: 29,
    label: "BGMI",
    participants: "02",
    timeLimit: "No limit",
    NoTeams: "Open Event",
    rules: ["Deatils Will be provided at the venue", "Offline"],
    Category: "Gaming",
    EntryFee: "200",
  },
  {
    id: 30,
    label: "Fashion Show",
    participants: "12",
    timeLimit: "10 Min",
    NoTeams: "3",
    rules: [
      "Karaoke is allowed",
      "Vulgarity and indecent acts on stage will lead to disqualification",
    ],
    Category: "Gaming",
    EntryFee: "1400",
  },
];

export const EventsDataDance = [
  {
    id: 1,
    label: "Dance Classical Solo",
    Category: "Dance",
    EntryFee: "150",
  },
  {
    id: 2,
    label: "Dance Classical Group",
    Category: "Dance",
    EntryFee: "500",
  },
  {
    id: 3,
    label: "Duet Dance",
    Category: "Dance",
    EntryFee: "300",
  },
  { id: 4, label: "Western Solo", Category: "Dance", EntryFee: "150" },
  {
    id: 5,
    label: "Choreography",
    Category: "Dance",
    EntryFee: "500",
  },
];

export const EventsDataMusic = [
  {
    id: 6,
    label: "Classic(Karnatic or Hindustani)",
    Category: "Music",
    EntryFee: "150",
  },
  { id: 7, label: "Western Solo", Category: "Music", EntryFee: "150" },
  {
    id: 8,
    label: "Instrumental Solo(percussion)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 9,
    label: "Instrumental Solo(Non percussion)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 10,
    label: "Light Music Solo(Indian)",
    Category: "Music",
    EntryFee: "150",
  },
  {
    id: 11,
    label: "Battle of bands(Indian)",
    Category: "Music",
    EntryFee: "500",
  },
  { id: 12, label: "Duet Singing", Category: "Music", EntryFee: "300" },
];

export const EventsDataTheater = [
  { id: 13, label: "Stand-Up Comedy", Category: "Theater", EntryFee: "150" },
  { id: 14, label: "Skit", Category: "Theater", EntryFee: "600" },
  { id: 15, label: "Mad-Ads", Category: "Theater", EntryFee: "600" },
  { id: 16, label: "Short Movie Making", Category: "Theater", EntryFee: "200" },
  { id: 17, label: "Movie Making", Category: "Theater", EntryFee: "500" },
];

export const EventsDataLiterary = [
  { id: 18, label: "Just a Minute", Category: "Literary", EntryFee: "100" },
  { id: 19, label: "Debate", Category: "Literary", EntryFee: "200" },
  { id: 20, label: "Dum Charades", Category: "Literary", EntryFee: "300" },
  { id: 21, label: "Quiz", Category: "Literary", EntryFee: "200" },
  {
    id: 22,
    label: "Antyakshari(Kannada)",
    Category: "Literary",
    EntryFee: "150",
  },
];
export const EventsDataFinearts = [
  { id: 23, label: "Face Painting", Category: "Fine arts", EntryFee: "200" },
  {
    id: 24,
    label: "Creative Photography",
    Category: "Fine arts",
    EntryFee: "100",
  },
  { id: 25, label: "Collage", Category: "Fine arts", EntryFee: "150" },
];
export const EventsDataGaming = [
  {
    id: 26,
    label: "Counter Strike(At Venue)",
    Category: "Gaming",
    EntryFee: "200",
  },
  { id: 27, label: "Valorant(Online)", Category: "Gaming", EntryFee: "250" },
  {
    id: 28,
    label: "Treasure Hunt(At Venue)",
    Category: "Gaming",
    EntryFee: "200",
  },
  {
    id: 29,
    label: "BGMI",
    participants: "02",
    EntryFee: "200",
  },
];

export const EventsDataFashion = [
  {
    id: 30,
    label: "Fashion Show",
    Category: "Gaming",
    EntryFee: "1400",
  },
];
